"""
Test: Browse Women Category

Verify guest user can browse products in the Women category.
Uses AAA pattern: Arrange, Act, Assert.

Generated by MCP Tool 6 (B.6 Simple E2E)
"""

import pytest
from resources.utilities import autologger
from roles.guest.guest_user import GuestUser
from pages.catalog.product_list_page import ProductListPage


class TestBrowseWomenCategory:
    """
    Test suite for browsing Women category.

    Uses existing framework classes:
    - GuestUser (Role) - browse_category() workflow
    - ProductListPage (POM) - has_products() state check
    """

    @pytest.fixture(autouse=True)
    def setup(self, web_interface, config):
        """Setup test fixtures."""
        self.web = web_interface
        self.config = config
        self.base_url = config.get("url", config.get("base_url", ""))
        self.product_list_page = ProductListPage(self.web)

    # ==================== TEST METHODS ====================

    @pytest.mark.catalog
    @autologger.automation_logger("Test")
    def test_browse_women_category(self):
        """
        Test that a guest can browse the Women category and see products.

        AAA Pattern:
        1. Arrange - Create GuestUser role
        2. Act - Call browse_category("Women")
        3. Assert - Verify products are displayed via POM
        """
        # Arrange
        guest = GuestUser(self.web, self.base_url)

        # Act - ONE workflow call, NO return value
        guest.browse_category("Women")

        # Assert - Via Page Object state-check methods (NOT return value)
        assert self.product_list_page.has_products(), "Products should be displayed in Women category"
        assert self.product_list_page.is_page_loaded(), "Product list page should be loaded"
